GEM-7 | Add integration tests and refactor
Group-Expense-Manager/service-template pull request #6
Opened 2024-03-24 22:39 UTC by lawos98

2024-03-26 19:11 UTC, pwgacek requested changes

2024-03-26 19:11 UTC, pwgacek commented on .github/workflows/ci.yml
> +          report_paths: '**/build/test-results/test/TEST-*.xml'
is this error intended behavior?
![Screenshot from 2024-03-26 19-15-23](https://github.com/Group-Expense-Manager/service-template/assets/80721230/36161ec6-7b08-49fe-a07c-61cee6cbf95e)

2024-03-26 19:11 UTC, pwgacek commented on src/test/kotlin/pl/edu/agh/gem/util/TestHelper.kt
> +fun createExampleProductRespone(
typo

2024-03-26 19:11 UTC, pwgacek commented on src/test/kotlin/pl/edu/agh/gem/internal/service/ProductServiceTest.kt
> +import io.kotest.matchers.should
unused import. weird ktlint did not find it

2024-03-26 19:11 UTC, pwgacek commented on settings.gradle.kts
> +rootProject.name = "exampleService"
think we should use the name of repo

2024-03-26 19:11 UTC, pwgacek commented on src/main/kotlin/pl/edu/agh/gem/external/persistence/MongoProductRepository.kt
> +import org.springframework.data.mongodb.core.findOne
unused import

2024-03-28 05:43 UTC, pwgacek requested changes

2024-03-28 05:43 UTC, pwgacek commented on src/integration/kotlin/pl/edu/agh/gem/integration/controler/ProductControllerIT.kt
> +        println("=====================================")
print

2024-03-29 06:05 UTC, lawos98 commented on src/integration/kotlin/pl/edu/agh/gem/integration/controler/ProductControllerIT.kt
> +import pl.edu.agh.gem.external.controller.SimpleErrorsHolder
```suggestion
```

2024-03-29 06:08 UTC, pwgacek approved these changes

2024-03-29 10:24 UTC, merged